
#Web/API config, for the primary api/web container that requires ingress
api:
  port: 80
  health_check_path: /health
  replicas: 1
  resources:
    limits:
      cpu: 300m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
    - name: "DEBUG"
      value: "true"
    - name: "DATABASE_NAME"
      value: "django"
    - name: "DATABASE_USER"
      value: "django"
    - name: "DATABASE_PASSWORD"
      value: "weak_password"
    - name: "DATABASE_SERVICE_HOST"
      value: "database"

database:
  port: 5432
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U postgres"]
    interval: 10s
    timeout: 5s
    retries: 5
  replicas: 1
  resources:
    limits:
      cpu: 300m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
    - name: "DEBUG"
      value: "true"
    - name: "DATABASE_NAME"
      value: "django"
    - name: "DATABASE_USER"
      value: "django"
    - name: "DATABASE_PASSWORD"
      value: "weak_password"
    - name: "DATABASE_SERVICE_HOST"
      value: "database"
