# Generated by Django 2.2.5 on 2019-09-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_store_api', '0002_auto_20190928_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
