# Generated by Django 2.2.5 on 2019-09-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_store_api', '0003_auto_20190928_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
